---

- name: Nginx | Repository | Add an nginx signing key
  become: yes
  apt_key:
    id: 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62
    url: https://nginx.org/keys/nginx_signing.key
    state: present

- name: Nginx | Repository | Add nginx binary repository
  become: yes
  apt_repository:
    repo: deb http://nginx.org/packages/mainline/debian/ {{ ansible_distribution_release }} nginx
    state: present
    filename: nginx

- name: Nginx | Repository | Add nginx src repository
  become: yes
  apt_repository:
    repo: deb-src http://nginx.org/packages/mainline/debian/ {{ ansible_distribution_release }} nginx
    state: present
    filename: nginx
