---
# tasks file for php
- name: PHP | Include vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
  tags: vars

- name: PHP | Prepare Install
  import_tasks: prepare_install.yml

- name: PHP | Phpbrew | Compile
  import_tasks: compile.yml

- name: PHP | Configure
  import_tasks: configure.yml

- shell: source /etc/profile; phpbrew path bin;
  args:
    executable: /bin/bash
  become: yes
  register: php_path_bin_result
  changed_when: false

- name: set php path
  set_fact:
    php_cli: "{{php_path_bin_result.stdout}}/php"
    cacheable: yes
  changed_when: false

- name: composer
  import_tasks: composer.yml

