- hosts: Linux
  gather_facts: False
  vars:
    ansible_host_key_checking: false
    ansible_ssh_extra_args: "{{ ansible_ssh_extra_args_base }} -o StrictHostKeyChecking=no -o ControlMaster=auto -o ControlPersist=60s -o ControlPath=~/.ansible/cp/ssh-%h-%p-%r"
    ansible_ssh_pipelining: False
  tasks:
  - name: allow ssh in ufw
    raw: 'ufw status | grep "Status: active" && ufw allow ssh && ufw disable && ufw --force enable'
    become: yes
#    register: output
    changed_when: false
    ignore_errors: yes
