---
# handlers file for postgresql
- name: postgresql restart
  become: yes
  service:
    name: postgresql
    state: restarted

- name: postgresql reload
  become: yes
  service:
    name: postgresql
    state: reloaded
